This project builds an end-to-end pipeline for analyzing engagement on YouTube videos by combining multilingual sentiment analysis, keyword extraction, and topic modeling. The workflow processes up to fifty videos at once, with a maximum of five thousand comments per video. To balance efficiency and representativeness, the pipeline uses a biased sampling strategy that prioritizes highly engaged comments (top liked, most replied, and most recent) while still incorporating a random sample for diversity.

The data collection stage relies on the YouTube Data API v3, using pagination to gather comments in batches of one hundred until reaching the five-thousand cap. Metadata such as title, description, channel, and publish date is also retrieved for context. For sentiment analysis, the current implementation uses the nlptown/bert-base-multilingual-uncased-sentiment model, which scores comments on a one-to-five star scale. While effective and working, this model was trained on Amazon product reviews, meaning it can misinterpret sarcasm, memes, or informal phrasing common in YouTube comments. An improvement would be to replace it with the cardiffnlp/twitter-roberta-base-sentiment-latest model, which is designed for social media text and better handles short-form, sarcastic, or emotionally mixed language, as well as incorporating other multilingual models such as xlm-roberta-base-sentiment to ensure stronger coverage across the top languages used on YouTube.

Keyword extraction is currently performed with a frequency-based CountVectorizer, but can be improved by using KeyBERT, which leverages semantic similarity from embeddings, combined with RAKE for multilingual support. To keep results clear and user-friendly, the number of visible keywords per video could also be limited to the top three. Topic modeling is handled by BERTopic with multilingual MiniLM embeddings, which identifies clusters of related discussion themes. However, with a larger minimum topic size, the topics can become scattered. By adjusting the parameter to a lower value, such as three, it would allow more coherent clusters.

The pipeline automatically detects the dominant languages in each set of comments, supporting English, Spanish, Hindi, Russian, German, French, Portuguese, Indonesian, Polish, Filipino, Turkish, Vietnamese, and more. The final outputs include an average sentiment score per video on a one-to-five scale, top keywords and discussion topics, and the distribution of languages among the audience. These results are compiled into a structured DataFrame for visualization and export.

Looking forward, several enhancements are possible. Sentiment analysis could be improved by swapping the current model with a social-media-pretrained RoBERTa to better handle informal and multilingual text. Keyword extraction could be refined by combining KeyBERT and RAKE for higher semantic accuracy, while also limiting the output for readability. The weighting of comments could also be tuned, for example by adjusting the log-scaling of likes and replies to give greater prominence to highly engaged comments. Beyond the modeling, the system could be integrated into a Chrome extension to display insights directly on YouTube, and scaled up with asynchronous requests and caching to handle more than fifty videos efficiently.
